export const broker = {
  mail: {
    AUTH_NOTIFICATION: 'AUTH_NOTIFICATION',
    NEW_ORDER_SUCCESS: 'NEW_ORDER_SUCCESS',
    PAYMENT_CONFIRMATION: 'PAYMENT_CONFIRMATION',
    PAYMENT_STATUS: 'PAYMENT_STATUS',
    SHIPPING_STATUS: 'SHIPPING_STATUS',
  },
  stock: {
    SALES_STOCK: 'SALES_STOCK',
    RETURN_SALES_STOCK: 'RETURN_SALES_STOCK',
  },
};
